### ISSUE TITLE
Thnx for this tweak

### ISSUE THREAD

**Issue by Blockr22** [TherionRO/YouTubeiVanced#1]
Hi, gd to know that there are more dev like u to support this community. I tested your app & it is working as expected. I don’t see any new features or bugs if we compare it to uYou+ but with latest youtube version which is great. uYou+ dev is little slow to update its app when it comes to github but it’s great to have him otherwise.

U can add in your description that it also supports 4k as this tweak has vp9 codec support.

Also can u improve on its downloads or have your own downloads manager built in as of like uYou cause that is really slow. I know people will love that. I used cercube at the time & it was great with fast download speed but then it was updated very less & it has banner ads.

Also it would be awesome if when installed that name & logo(Shown in pictures is awesome) of your tweak shows as iVanced rather than YouTube since Vanced was a known name in android world & people like me using altstore or Sidestore have no other way to change the name of the app.

Thnx again for supporting the community.

**Comment by TherionRO** [comment]
Hey! Thank you very much for all the suggestions. I will take all of them in consideration,and yes,I just started developing things for iOS as I was and still is a mainly Android developer.I created this as a rolling release,always based on the latest version of youtube but with all uYou and uYouPlus features and other tweaks.

😊✌️

**Comment by korboybeats** [comment]
> Hey! Thank you very much for all the suggestions. I will take all of them in consideration,and yes,I just started developing things for iOS as I was and still is a mainly Android developer.I created this as a rolling release,always based on the latest version of youtube but with all uYou and uYouPlus features and other tweaks.
> 
> 😊✌️

This "release" of "yours" is the exact same thing as uYouPlus. Why are you stealing it and renaming it as something different? The only thing "different" is the updated YouTube version, which anyone can also make by getting a decrypted YouTube link from [armconverter](https://armconverter.com/decryptedappstore/us) then forking uYouPlus and building an IPA from the 'Actions' tab. New YouTube versions for uYouPlus get uploaded on AppDB too anyways. I don't get it.

**Comment by swaggyP36000** [comment]
> 

Yeah I tested this: it's literally a 1:1 of [uYou+](https://github.com/qnblackcat/uYouPlus) on a slightly higher YouTube. Same features, same bugs. Not sure what to make of this, but until this dev makes any kind feature updates/improvements, theres no reason to pay attention to this repository

**Comment by TherionRO** [comment]
> > Hey! Thank you very much for all the suggestions. I will take all of them in consideration,and yes,I just started developing things for iOS as I was and still is a mainly Android developer.I created this as a rolling release,always based on the latest version of youtube but with all uYou and uYouPlus features and other tweaks.
> > blushv
> 
> This "release" of "yours" is the exact same thing as uYouPlus. Why are you stealing it and renaming it as something different? The only thing "different" is the updated YouTube version, which anyone can also make by getting a decrypted YouTube link from [armconverter](https://armconverter.com/decryptedappstore/us) then forking uYouPlus and building an IPA from the 'Actions' tab. New YouTube versions for uYouPlus get uploaded on AppDB too anyways. I don't get it.

I will edit and apply some patches to uYou+.And no,this is not a copy and I am not stealing a open source project.If you readed the github readme you can clearly see that I stated "THIS IS A FORK OF UYOU+" and I gaved all the credits to the authors.I didnt put my name on anything,I just changed the name to iVanced because I like it.But again,this is a opensource project and anyone can edit it and publish it as long as they give credits.And if you can build it no one can,there are a lot of people that dont even know to read the building wiki and maybe they want the latest features from YouTube.People like you kill other open source projects,and people like you are the reason for AetherSX2 termination.

**Comment by Blockr22** [comment]
@TherionRO Buddy Don’t let these negative comments get in ur head. U do u, everyone knows its open source & so many other makes forks of these projects all the time. If u have the knowledge, its always appreciated to gets latest updates & new features and it should help u grow aswell.

**Comment by swaggyP36000** [comment]
> @TherionRO Buddy Don’t let these negative comments get in ur head. U do u, everyone knows its open source & so many other makes forks of these projects all the time. If u have the knowledge, its always appreciated to gets latest updates & new features and it should help u grow aswell.

Per my comment: "until this dev makes any kind feature updates/improvements, theres no reason to pay attention to this repository". I have already starred the repo and am following it for any future updates, but at the moment it is as I said, just a copy uYou+'s features, with an overall name change, on a slightly higher version of YouTube.

**Comment by korboybeats** [comment]
> > > Hey! Thank you very much for all the suggestions. I will take all of them in consideration,and yes,I just started developing things for iOS as I was and still is a mainly Android developer.I created this as a rolling release,always based on the latest version of youtube but with all uYou and uYouPlus features and other tweaks.
> > > blushv
> > 
> > 
> > This "release" of "yours" is the exact same thing as uYouPlus. Why are you stealing it and renaming it as something different? The only thing "different" is the updated YouTube version, which anyone can also make by getting a decrypted YouTube link from [armconverter](https://armconverter.com/decryptedappstore/us) then forking uYouPlus and building an IPA from the 'Actions' tab. New YouTube versions for uYouPlus get uploaded on AppDB too anyways. I don't get it.
> 
> I will edit and apply some patches to uYou+.And no,this is not a copy and I am not stealing a open source project.If you readed the github readme you can clearly see that I stated "THIS IS A FORK OF UYOU+" and I gaved all the credits to the authors.I didnt put my name on anything,I just changed the name to iVanced because I like it.But again,this is a opensource project and anyone can edit it and publish it as long as they give credits.And if you can build it that doesnt mean everyone can,theres a lot of people that dont even know to read the building wiki and maybe they want the latest features from YouTube.People like you kill other open source projects,and people like you are the reason for AetherSX2 termination.

I have no idea what AetherSX2 is but ok. If people don't even know how to read the building wiki, they will forsure not bother reading the credits at the bottom and just go straight to the releases, thinking this is an entire new modded YouTube app created by you. You even labeled yourself as the developer on your AppDB post instead of Qn, the creator of uYouPlus, when it's the exact same 1:1 copy of uYouPlus with absolutely nothing added.

**Comment by TherionRO** [comment]
> > I will edit and apply some patches to uYou+.And no,this is not a copy and I am not stealing a open source project.If you readed the github readme you can clearly see that I stated "THIS IS A FORK OF UYOU+" and I gaved all the credits to the authors.I didnt put my name on anything,I just changed the name to iVanced because I like it.But again,this is a opensource project and anyone can edit it and publish it as long as they give credits.And if you can build it that doesnt mean everyone can,theres a lot of people that dont even know to read the building wiki and maybe they want the latest features from YouTube.People like you kill other open source projects,and people like you are the reason for AetherSX2 termination.
> 
> I have no idea what AetherSX2 is but ok. If people don't even know how to read the building wiki, they will forsure not bother reading the credits at the bottom and just go straight to the releases, thinking this is an entire new modded YouTube app created by you. You even labeled yourself as the developer on your AppDB post instead of Qn, the creator of uYouPlus, when it's the exact same 1:1 copy of uYouPlus with absolutely nothing added. There is no reason for this repo until something is added.

Labeling on appdb doesn't mean anything.By your logic open source projects should be the same as the proprietary ones and no one should touch them or update just a small part of it.Again,read the whole ivanced repo "Note : iVanced for YouTube is a fork of uYou/uYouPlus based on the latest version of youtube,a rolling release with extended life support and likely more unstable. [iVanced Source Code here](https://github.com/qnblackcat/uYouPlus) .Keep in mind that I cannot opensource the uYou tweak and the YouTube app as this is not legal." this is not meant to be a whole redesign of uYou or uYou+,nor a revolutionary new youtube mod.This is just meant to updated as fast as possible as the original uYouPlus author have other things to do and don't have the time to update it every time google pushes a new version. I just started getting into iOS applications and this is a good start for me,atleast you should support the fact that I am trying to give iOS a chance,as all my life I created things for android.And also where I stated that ivanced is a whole new modded app created by me? Tell me and I will remove it,maybe I was drunk when I "wrote" something like this.

**Comment by TherionRO** [comment]
> > I will edit and apply some patches to uYou+.And no,this is not a copy and I am not stealing a open source project.If you readed the github readme you can clearly see that I stated "THIS IS A FORK OF UYOU+" and I gaved all the credits to the authors.I didnt put my name on anything,I just changed the name to iVanced because I like it.But again,this is a opensource project and anyone can edit it and publish it as long as they give credits.And if you can build it that doesnt mean everyone can,theres a lot of people that dont even know to read the building wiki and maybe they want the latest features from YouTube.People like you kill other open source projects,and people like you are the reason for AetherSX2 termination.
> 
> I have no idea what AetherSX2 is but ok. If people don't even know how to read the building wiki, they will forsure not bother reading the credits at the bottom and just go straight to the releases, thinking this is an entire new modded YouTube app created by you. You even labeled yourself as the developer on your AppDB post instead of Qn, the creator of uYouPlus, when it's the exact same 1:1 copy of uYouPlus with absolutely nothing added. There is no reason for this repo until something is added.

"iVanced for YouTube is a modded app providing more features over the standard YouTube app.
iVanced is maintained by TherionRO on github:
https://github.com/TherionRO/YouTubeiVanced" The first part on appdb desc,what is wrong with this? I think this is the part that annoys you. iVanced is a modded app providing more features over the original youtube app,not uYou or uYouPlus. iVanced is maintained by therionro on github,not created,I dont see what is wrong with it.

**Comment by korboybeats** [comment]
> And also where I stated that ivanced is a whole new modded app created by me?

I never said you stated that iVanced is a whole new modded app created by you. I said, people will think it's a whole new modded YouTube app created by you. I just think it's weird for this to exist as an entirely new redesign and name when there is nothing new added. Anyways, that's all I have to say, won't bother anymore.
