### ISSUE TITLE
Issues caused by broken dependencies - thread

### ISSUE THREAD

**Issue by DiasporaLive** [TherionRO/YouTubeiVanced#10]
as of today,some dependencies are broken and the ipa file is unstable.

Broken features :
-Shorts just won't work.Not even opening them from the home page
-Dependencies are broken so rebuilding won't work
-Autoplay is not working for some people
-Logout when you simply upgrade using the .ipa,login works as i have a developer licence from apple but third party sideloading wont natively work,you need shortcuts script.

If someone finds other bugs please type them in the comments.

@TherionRO

**Comment by DiasporaLive** [comment]
also everyone should use 18.03.3 for now

**Comment by TherionRO** [comment]
Alright,I will look into the dependencies aswell.Thanks!

**Comment by TherionRO** [comment]
Shorts crash is now fixed.
