### ISSUE TITLE
Notification not working 

### ISSUE THREAD

**Issue by Blockr22** [TherionRO/YouTubeiVanced#13]
Its keeps on saying turn on notifications even though they are on in notifications section of the app.

**Comment by TherionRO** [comment]
Hey,I don't have this issue. Have you updated to iVanced from another modded youtube app/outdated uYou+ ? Have you tried completely uninstalling the modded youtube app and re-sideload it brand new?

**Comment by Blockr22** [comment]
Hey, so i update from ivanced older version to this newer version. I had to uninstall/delete original YouTube in order to fix, notifications & connect to device. But it’s working as intended now.
