### ISSUE TITLE
What’s the point of this tweak?

### ISSUE THREAD

**Issue by ShadowRoi** [TherionRO/YouTubeiVanced#2]
Yes you want to contribute into helping the YouTube experience becoming better and we all appreciate this. But why a fork of uYouPlus?? uYou is not open source so nothing can be included but uYouPlus was made for the purpose that everyone can contribute and make it better. So why are you making a hole different tweak instead of just making pull requests to uYouPlus??? 

This will only cause more confusion

**Comment by TherionRO** [comment]
Hey there! Yes,you are right and I knew that it will create more confusion in the community before creating the repo. I wanted to redesign more parts of uYouPlus and include some other tweaks.Sadly,this will take some time and I think I created the repo and launched the ipa way too fast and it is basically the same at this time. I am really impatient :)
