### ISSUE TITLE
Bring Back the Custom Icon 

### ISSUE THREAD

**Issue by meechgalhuquot** [TherionRO/YouTubeiVanced#23]
The last few updates have just had the default YouTube app icon, can you back the black and blue icon?  I like the way it looks more than the default one a nice little touch to show it's not stock YouTube. If not, will you  provide an icon file so I can manually override it in AltStore?

**Comment by TherionRO** [comment]
Hey! I was planning to bring back the iVanced logo directly into the build,but I didnt really mess up with the logo yet. I uploaded the iVanced logo on this repo,here's the link : https://github.com/TherionRO/YouTubeiVanced/blob/main/github-assets/images/iVanced.png

**Comment by meechgalhuquot** [comment]
Excellent, thanks!

**Comment by TherionRO** [comment]
Update : iVanced 19.08.2 has the iVanced logo instead of the stock youtube one.
