### ISSUE TITLE
Battery drain when running 4k video 

### ISSUE THREAD

**Issue by Coolman77i** [TherionRO/YouTubeiVanced#24]
When running a 4k video in 60FPS or HDR the battery drains fast I have an iPhone 11 pro when I run a 4k video on the Official YouTube app it doesn't drain or heat up or studder please fix this issue I love the app but fix the battery drain issue

**Comment by TherionRO** [comment]
Hey! Did u changed any other settings in the ivanced app? Or are u using the default config?

**Comment by Coolman77i** [comment]
I used the VP9 configurations to enable 4K 60 FPS but it drains the battery so I turned it off

**Comment by TherionRO** [comment]
Watching videos in 4K increases the bitrate of the video,its totally normal for your battery to drain a bit faster compared to watching videos in 1080p. U should stick to HD/FullHD as ur iphone panel doesnt even support 4K,the only benefit is the higher bitrate but the difference isnt huge,use 4K only on a 4K panel device.
