### ISSUE TITLE
YouTube short crashing

### ISSUE THREAD

**Issue by DamnBoi706** [TherionRO/YouTubeiVanced#7]
YouTube short is crashing on the latest version (18.04.03) I've downgraded to 18.03.03 and now it works just fine

**Comment by TherionRO** [comment]
Hey there! Thanks for telling me,I was not aware of this as I just disable the shorts tab because I dont really use them.I will take a look into this!

**Comment by tupac55** [comment]
I have the same issue

**Comment by TherionRO** [comment]
Shorts crash is now fixed.
