### ISSUE TITLE
My account got signed out

### ISSUE THREAD

**Issue by Blockr22** [TherionRO/YouTubeiVanced#8]
Google kicked me out & its signed out somehow automatically after this update

**Comment by TherionRO** [comment]
We are aware that modded youtube apps on iOS devices are problematic with the login feature. What's the signing method you are using? Altstore? online signature tool like signulous with a purchased developer account? At the moment there are a few things you can do to bypass this and login into a modded youtube app like the safari trick or using the shortcut script.

**Comment by Blockr22** [comment]
Using SideStore to sideload & shortcut script to login. After updating the app it just kicked me out of my account & have to use the shortcut again to sign in
